name: 'subscription_project'
version: '1.0.0'
profile: 'subscription_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# This is where we tell dbt how to handle your specific folders
models:
  subscription_project:
    staging:
      +materialized: view
      +enabled: true
    intermediate:
      +materialized: ephemeral
      +enabled: true
    marts:
      +materialized: table
      +enabled: true